services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    networks: 
      - docker-app
    depends_on: 
      - node

  firebase:
    build: ./firebase  # Directory containing Dockerfile (case-sensitive)
    image: rambabusaravanan/firebase  # Optional - only needed if you want to tag the built image
    ports:
      - "4000:4000"   # Firebase Emulator Suite UI
      - "8080:8080"   # Firebase Hosting
      - "5001:5001"   # Firebase Functions
      - "9000:9000"   # Firebase Database
      - "8085:8085"   # Firebase Auth
      - "9199:9199"   # Firebase Storage
    environment:
      FIREBASE_PROJECT_ID: "farmx-1381c"
      FIREBASE_DATABASE_EMULATOR_HOST: "firebase:9000"
      FIREBASE_AUTH_EMULATOR_HOST: "firebase:8085"
      FIREBASE_STORAGE_EMULATOR_HOST: "firebase:9199"
    volumes: 
      - firebase-data:/home/node/firebase-project
    networks:
      - docker-app
    restart: always

  node:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: node_cont
    restart: always
    depends_on: 
      - firebase
    networks:
      - docker-app
    volumes: 
      - ./:/app                # Mount current directory
      - /app/node_modules      # Keep node_modules separate
      - firebase-data:/app/firebase-data  # If node needs access to firebase data

networks:
  docker-app:
    driver: bridge

volumes:
  firebase-data: