services:
  nginx:
    build:
      context: ./nginx
      target: dev
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    networks: 
      - docker-app
    depends_on: 
      - node

  firebase:
    build: ./firebase
    image: rambabusaravanan/firebase
    ports:
      - "4000:4000"
      - "8080:8080"
      - "5001:5001"
      - "9000:9000"
      - "8085:8085"
      - "9199:9199"
    environment:
      FIREBASE_PROJECT_ID: "farmx-1381c"
      FIREBASE_DATABASE_EMULATOR_HOST: "firebase:9000"
      FIREBASE_AUTH_EMULATOR_HOST: "firebase:8085"
      FIREBASE_STORAGE_EMULATOR_HOST: "firebase:9199"
    volumes: 
      - firebase-data:/home/node/firebase-project
    networks:
      - docker-app
    restart: always

  node:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    container_name: node_cont
    restart: always
    depends_on: 
      - firebase
    networks:
      - docker-app
    volumes: 
      - ./:/app
      - firebase-data:/app/firebase-data
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: sh -c "pnpm install && pnpm run dev"

networks:
  docker-app:
    driver: bridge

volumes:
  firebase-data: